### ISSUE TITLE
Publish for scala 2.12

### ISSUE THREAD

**Issue by fommil** [sirthias/parboiled2#170]
You missed 2.10 last time can you please release it (java 6 or 7) at the same time please? Ensime still needs it for the cross build. And also spray-json :-)

**Comment by sirthias** [comment]
@fommil Ok, can do. What exactly do you need? 2.12 or 2.10? The ticket title and your description are a bit in disagreement on this... :)

**Comment by fommil** [comment]
Both :-P actually one version with cross build for 2.10, 2.11 and 2.12.

**Comment by SethTisue** [comment]
@sirthias I would like to add parboiled2 to the Scala 2.12 community build, but I would prefer to wait until you've published for 2.12.0-RC1, so I know that any needed changes to your sources and/or build definition are already in place.

if you find that any of your upstream dependencies haven't published for 2.12.0-RC1, let me know here and we'll go pester them about it together :-)

**Comment by sirthias** [comment]
Just tried (cross-)upgrading to 2.12.0-RC1 but shapeless 2.3 for 2.12.0-RC1 has not yet been released. Looking at the shapeless master it appears as if @milessabin still has it on 2.12.0-M5.

**Comment by milessabin** [comment]
There were a number of regressions in Scala 2.12.0-RC1 which made it impractical to publish shapeless for that release. There will be a release for RC2.

**Comment by sirthias** [comment]
Ok. Thanks, Miles! I'll wait for RC2 then.

**Comment by lambdista** [comment]
Hi @sirthias, could you publish 2.10 meanwhile? Trying to cross build my project I get an unresolved dependencies path for `org.parboiled:parboiled_2.10:2.1.3`

**Comment by sirthias** [comment]
@fommil @lambdista Sorry for taking so long to get the 2.1.3 cross-build for 2.10 published. It is now on sonatype and should appear on maven central soon. Cheers!

**Comment by fommil** [comment]
awesome, thanks! BTW, heads up that we might be moving over to fastparse because we're planning on using `scala.meta` and it's a transitive dependency... and having THREE parsers on our classpath is a bit crazy. If you see the change, don't take it personally :smile:

**Comment by sirthias** [comment]
No worries at all! In fact I would nowadays recommend fastparse over any version of parboiled.
So, good move!

**Comment by SethTisue** [comment]
Shapeless 2.3.2 for 2.12.0-RC2 is now on Maven Central

**Comment by sirthias** [comment]
Ok, just pushed parboiled2 2.1.3 for 2.12.0-RC2 to sonatype. Should be on Maven Central soon.

**Comment by theon** [comment]
Now 2.12.0-RC2 has become the official 2.12.0, could we get a released pushed for 2.12.0. I guess this is waiting on: https://github.com/milessabin/shapeless/issues/651

**Comment by xuwei-k** [comment]
> I guess this is waiting on: milessabin/shapeless#651

- https://twitter.com/milessabin/status/793753359744430080
- http://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.2/

**Comment by theon** [comment]
On, nice. Thanks @xuwei-k

**Comment by milessabin** [comment]
Sorry, I should have bumped this thread when I published.

**Comment by sirthias** [comment]
Ok, done. On sonatype on thus soon on maven central.

**Comment by theon** [comment]
Thanks @sirthias

**Comment by jmzhang** [comment]
Hi, I'm upgrading a scalajs project to 2.12, but still getting a ResolveException for org.parboiled#parboiled_sjs0.6_2.12;2.1.3. Could you publish this as well?

**Comment by sirthias** [comment]
Ok, just pushed `org.parboiled#parboiled_sjs0.6_2.12;2.1.3` to sonatype.
